# -*- coding: utf-8 -*-
"""gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YW5nj1MgzFs2qo-aYsVxe-v1GYNE_AH8
"""
muscles = ["biceps",
                "calves",
                "chest",
                "forearms",
                "glutes",
                "hamstrings",
                "lats",
                "lower_back",
                "middle_back",
                "quadriceps",
                "traps",
                "triceps"]

muscles_input = ", ".join(muscles)

print(muscles_input)

days = {
    'monday':0,
    'tuesday': 45,
    'wednsday': 120,
    'thursday': 120,
    'friday': 45
}

import google.generativeai as genai

genai.configure(api_key="AIzaSyBWQJ6XQ8rUZlH-V2wMXTUFLbtTvqgL3zI")
model = genai.GenerativeModel('gemini-1.5-pro-latest')

AI_PROMPT = f"""Can you create a workout routine Monday for {days['monday']} mins, 
            Tuesday for {days['tuesday']} mins, 
            Wednesday for {days['wednsday']} mins, 
            Thursday for {days['thursday']} mins,
            Friday for {days['thursday']} mins, using all these muscles groups {muscles_input} ?"""

response = model.generate_content(AI_PROMPT)
print(response.text)